Basics of lists and arrays
-----------------------------------
Let us start with the same boilerplate code:

In [3]:
from __future__ import print_function, division
from sympy.interactive import printing
printing.init_printing(use_latex='mathjax')

The default solution for doing numerical linear algebra in Python is NumPy, which provides a low-level infrastructure for the calculations, and SciPy, which has many high-level functions. These are efficient, fast, and quality-checked packages that evolve fast. There are, of course, other options. For instance, [Theano](http://deeplearning.net/software/theano/) allows a 140x faster calculations of certain tensor product operations using GPUs. We focus on NumPy and SciPy for the rest of this tutorial, but do explore other options. We start with importing all functions:

In [1]:
from numpy import *
from scipy import *

Lists and NumPy arrays are different. The latter is very similar to matrices and vectors in MATLAB. A list can be heterogeneous and vary in size, whereas a NumPy array has a fixed type and size. Here is a valid list of a float, a string, and a function:

In [4]:
l = [sqrt(2), "random text", fft]

A NumPy array of floats, for instance:

In [5]:
a = array([0.1, 0.2, 0.3])

This is a modicum more inconvenient than the MATLAB-style input of vectors. The designers of NumPy could have opted for MATLAB-style input, but this casting of arrays from list is more consistent with the language. For matrices, we have

In [22]:
M = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


With arrays, we can do straightforward numerical operations. These are vectorized, which means they execute extremely fast:

In [11]:
print(a+1)
print(2*a)
print(sqrt(a))
print(a*a)

[ 1.1  1.2  1.3]
[ 0.2  0.4  0.6]
[ 0.31622777  0.4472136   0.54772256]
[ 0.01  0.04  0.09]


The last one is worth extra attention: by default, multiplication is element-wise. For a dot product, we must call the dot function:

In [12]:
dot(a, a)

0.14

We have some familiar constructs to create vectors and matrices:

In [14]:
print(zeros(2))
print(ones(2))
print(eye(2))

[ 0.  0.]
[ 1.  1.]
[[ 1.  0.]
 [ 0.  1.]]


A single element of lists and arrays is retrieved the same way. Reverse indexing also works:

In [14]:
print(l[0], a[0], a[-1])

1.41421356237 0.1 0.3


NumPy arrays also support slicing, which works identically to MATLAB. Note, however, that indexing starts with 0 and the last index is non-inclusive:

In [9]:
print(a[1:3])
print(M[:,2])

[ 0.2  0.3]
[3 6 9]


We can also take, say, every third element in an array:

In [13]:
b = arange(20)
b[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

We can also have conditional statements as indices:

In [15]:
b[b%5 == 0]

array([ 0,  5, 10, 15])

Reshaping is also allowed:

In [17]:
print(b)
print(b.reshape(4, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


There are a few other convenience functions built in the arrays:

In [19]:
print(b.sum(), b.min(), b.max())

190 0 19


In matrices, we can do these row-wise or column-wise:

In [20]:
M.sum(axis=0) # Sum of each column

array([12, 15, 18])

SciPy
-------
Sparse matrices, optimization, basic signal processing, interpolation, Fourier transforms, statistics, and even more linear algebra reside in this package. There are usually more featureful packages for most of the functionality, but SciPy is a decent common denominator. SciPy builds on NumPy, and this is true for most other scientific packages: NumPy is indispensable, the rest depends on what you want to do and how much control you want over the algorithms. For instance, using SciPy, the transfer-matrix method is about a hundred lines of straightforward code.

As an example, we look at optimization by a quasi-Newton method, the Broyden-Fletcher-Goldfarb-Shanno (BFGS) algorithm, which is the same as MATLAB uses in ``fminunc``. The following [example](https://docs.scipy.org/doc/scipy-0.14.0/reference/tutorial/optimize.html) is from the SciPy tutorial. We import the ``minimize`` function and define a function with an initial point:

In [25]:
from scipy.optimize import minimize
def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)
x0 = array([1.3, 0.7, 0.8, 1.9, 1.2])

In [29]:
res = minimize(rosen, x0)
print(res.x)

[ 0.99999933  0.99999866  0.99999727  0.99999449  0.99998874]


QuTiP
-------

Convex optimization and semidefinite programmes
---------------------------------------------------------------